name: llm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pillow
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - rich
  - pytest
  - opencv
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - open_clip_torch
      - datasets
      - modelscope
      - huggingface_hub
      - transformers
      - accelerate
